apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vivek-dev-workspace
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: shared-vast
  volumeMode: Filesystem
