#xinput --set-prop 8 154 1.4,0,0,0,1.4,0,0,0,1

# Set keyboard delay and rate
xset r rate 300 50

# Statusbar
while true; do
   xsetroot -name "$( date +" %d/%m/%y %R" )"
   sleep 20s    # Update time at interval
done &

exec dwm
