#xinput --set-prop 8 154 1.4,0,0,0,1.4,0,0,0,1

# Keyboard
setxkbmap -option 'ctrl:swapcaps_hyper'
setxkbmap -option 'altwin:swap_alt_win'
xcape -e 'Control_L=Escape'
xcape -e 'Shift_L=Shift_L|9'
xcape -e 'Shift_R=Shift_R|0'

# Set keyboard delay and rate
xset r rate 300 50

# redshift
redshift -l 1.27:103.84 &

# picom
picom -b

# set background
background

# dunst (notifications)
dunst &

# nextcloud
nextcloud &

# zotero
zotero &

# Statusbar
while true; do
   xsetroot -name "$( date +" %d/%m/%y %R" )"
   sleep 20s    # Update time at interval
done &

exec dwm
